// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  // SignInButton, // You might not need these here if they're used within AppHeader or other components
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs';
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";

// Import your AppHeader component here
// The path is relative to app/layout.tsx
import AppHeader from './(routes)/dashboard/_components/AppHeader';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Travel Voice Agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Render the AppHeader (your navbar) here. It will appear on ALL pages. */}
          <AppHeader />

          {/* Add padding to push content down */}
          <div className="pt-16 pb-16"> {/* Adjust 'pt-16' based on your navbar's height */}
            <Provider>
              {children} {/* `children` represents the actual page content */}
              <Toaster />
            </Provider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
